1. Indicizzazione booleana

Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: 2, 3, 5, 7, 11, 13, 17, 19.
Utilizza un test logico (ad esempio >, <, ==, !=) per selezionare tutte le voci del vettore maggiori di 10.
Utilizza un test logico per selezionare tutti i numeri primi pari dalla lista.

In [19]:
import numpy as np

numeri_primi=np.array([2,3,5,7,11,13,17,19])

print("1. La mia lista e':", numeri_primi)

primi_10=numeri_primi[np.where(numeri_primi>10)]

print("2. I numeri maggirori di 10 sono",primi_10)

pari=numeri_primi[np.where(numeri_primi%2==0)]

print("3. I numeri pari sono",pari)


1. La mia lista e': [ 2  3  5  7 11 13 17 19]
2. I numeri maggirori di 10 sono [11 13 17 19]
3. I numeri pari sono [2]


2. Operazioni su array
Crea un array a, 2D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente la sua 2ª e 4ª riga, e c contenente solo la 3ª. Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [26]:
a=np.arange(8).reshape((4,2))

print("1. Array a: ",a)

b=a[[1,3]]

print("2. Array b:",b)

c=a[[2]]

print("3. Array c:",c)



1. Array a:  [[0 1]
 [2 3]
 [4 5]
 [6 7]]
2. Array b: [[2 3]
 [6 7]]
3. Array c: [[4 5]]


3. Seleziona il numero più vicino a 0.5 in un array casuale
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1]. Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [ ]:

a=np.random.rand(10,3)

print(a)





[[0.69664768 0.71729169 0.12224858]
 [0.8181736  0.7961288  0.13829835]
 [0.32069347 0.72478133 0.15563473]
 [0.11447153 0.76360538 0.01765835]
 [0.06438786 0.59315141 0.31790761]
 [0.79616554 0.29759126 0.87522629]
 [0.46825294 0.58631695 0.28200734]
 [0.26853075 0.85791196 0.49583865]
 [0.10849339 0.7307983  0.34676306]
 [0.21928574 0.49441922 0.85830562]]
[0.71729169 0.8181736  0.72478133 0.76360538 0.59315141 0.87522629
 0.58631695 0.85791196 0.7307983  0.85830562]


4. Analisi della Frequenza Cardiaca con NumPy

In [48]:
a=np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

minimo=min(a)
print("minimo:",minimo)
massimo=max(a)
print("massimo:",massimo)

b=np.array([a>120])

print(b)
maggioridi120=a[np.where(a>120)]

conteggio=a.size
maggioridi120.size
percentuale=(maggioridi120.size/a.size)*100
print(percentuale)



minimo: 60
massimo: 164
[[False False False False  True  True  True  True  True  True  True  True
   True  True  True False False False False False False]]
52.38095238095239


5. Manipolazione di vettori

In [68]:
a=np.array([50000,105250,55000,89000],dtype=float)

costo_personale=sum(a)

print("costo personale inziale: ",costo_personale)
massimo=max(a)
a[np.where(a==massimo)]=massimo+((massimo*15)/100)
a[np.where(a==50000)]=50000+((50000*20))/100
a[np.where(a==89000)]=89000+((89000*20))/100
a[np.where(a==55000)]=55000+((55000*20))/100
print("nuovi stipendi: ",a)

costo_personale_modificato=sum(a)

print("costo personale modificato:",costo_personale_modificato)

costo_aumento=costo_personale_modificato-costo_personale

print("C'è stato un aumento di ",costo_aumento)



costo personale inziale:  299250.0
nuovi stipendi:  [ 60000.  121037.5  66000.  106800. ]
costo personale modificato: 353837.5
C'è stato un aumento di  54587.5


6. Valori di Co2

In [ ]:
valori=np.loadtxt('emissioni.txt',dtype=float)

totale =sum(valori)
print("totale:",totale)
somma=0
for x in range(0,valori.size):
    if x>18.:
        somma+=x

print("somma valori sopra le 18t:",somma)

frazione=somma/totale

print(frazione)

totale: 2444.8700000000013
somma valori sopra le 18t: 19729
8.069549710209536


7. Analisi di una matrice

In [93]:
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

filtrati = survey_matrix[survey_matrix[:, 2] >= 12,1]  #righe: survey_matrix[:, 2] >= 12 ovvero solo quelle che hanno il valore >12 poi per selezionarmi solo le colonne #colonne ,1
print(filtrati)

sum(filtrati)

np.mean(filtrati)

[52000 63000 58000]


57666.666666666664

8. Rimpiazzare gli outliers


In [ ]:
ages = np.array([999, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])


np.delete(ages,np.where(ages==999))






array([108,  75,  63,  62,  66,  90,  98,  97,  92,  60, 107,  90,  71,
        97,  86,  55,  55,  98,  57,  96, 104,  96,  94,  72,  98, 111,
        98,  89,  69,  77,  92,  85, 101,  93, 100,  90, 101,  96,  98,
        87, 106,  86, 108,  55,  67,  65,  68,  59,  67,  72,  57,  79,
        95,  67,  86,  70,  91, 111,  67,  75,  59,  88,  90,  99,  94,
        65, 111, 103, 100,  70,  63,  65, 100, 110,  70,  57,  75,  56,
       104, 111,  90,  74, 100,  90,  86,  88,  99,  58, 103,  88, 103,
        64,  96, 105,  89,  83,  65, 100,  62,  73, 105,  83, 105,  58,
        96,  77,  74,  95, 109,  91, 101,  91,  63, 111,  97, 108,  75,
        77,  73,  58,  94,  83,  90,  61, 110, 107, 105,  85,  64,  66,
        71, 107, 105,  72,  78,  66, 100, 102,  72,  74,  68,  73,  72,
        90,  93,  99,  55,  92,  83,  58,  71,  89,  75,  98,  87,  78,
        97,  71, 106,  83,  58,  81, 100,  72,  93,  70,  65,  60,  95,
       107,  94,  77,  87,  90,  82,  56,  99, 107,  86,  56,  7

9.Generazione random di storie
