Sto scrivendo

In [4]:
a=0
b=5
print(a+b)
print("ciao")

%timeit [a*b]

5
ciao
38.5 ns ± 1.17 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


LIST COMPRENTION




In [ ]:
numeri = []

for x in range(10):
    numeri.append(x*x)
    
#con la list comprention

numeris= [x*x for x in range(10)]

print("i numeri della list comorendion" ,format(numeris))

pari = [x for x in range(11) if x%2==0]

print(pari)

#controllare tutti i valori di una lista sono all'interno di un altra lista

prima=[1,2,3]

seconda=[2,3]

all(mio in seconda for mio in prima) #dato che non è presente il numero 1 il programma darà come risultato "false"

#creazione di una funzione più velocemnte tramite lambda

funzione_Somma= lambda x,y:x+y

ris=funzione_Somma(2,3)

print(ris)

i numeri della list comorendion [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10]
5


esempio con list comprention


In [ ]:
lista= [1000,2000]

def calcola(salariobase, bonus=.1):
    return salariobase* (1+bonus)

salario= [calcola(salario) for salario in lista]

print(salario)

[1100.0, 2200.0]


Stesso esempio con lambda

In [16]:
lista= [1000,2000]
funzione = [(lambda salariobase,bonus=.1: salariobase*(1+bonus))(salario) for salario in lista]



print(funzione)

[1100.0, 2200.0]


Modulo

per creare un file si fa:

In [ ]:
%%writefile modulo.py
# per modificarlo devo fare %%writefile -a modulo.py
def somma(x,y):
    return x+y

Writing modulo.py


Per usare il mio modulo

In [18]:
import modulo

modulo.somma(1,2)

3

NumPy

In [ ]:
#installazione 

%conda install numpy

#importazione


import numpy as np





Channels:
 - defaults
Platform: osx-arm64
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


array([1, 2, 3, 4, 5])

In [ ]:
#uso su array

a=np.array([1,2,3,4,5])

print(a)

#per capire il tipo di dato

a.dtype

#posso dire io che tipo di dato voglio

afloat=np.array([1,2],dtype="float")

afloat



[1 2 3 4 5]


array([1., 2.])