Sto scrivendo

In [2]:
a=0
b=5
print(a+b)
print("ciao")

%timeit [a*b]

5
ciao
33.6 ns ± 0.463 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


LIST COMPRENTION




In [3]:
numeri = []

for x in range(10):
    numeri.append(x*x)
    
#con la list comprention

numeris= [x*x for x in range(10)]

print("i numeri della list comorendion" ,format(numeris))

pari = [x for x in range(11) if x%2==0]

print(pari)

#controllare tutti i valori di una lista sono all'interno di un altra lista

prima=[1,2,3]

seconda=[2,3]

all(mio in seconda for mio in prima) #dato che non è presente il numero 1 il programma darà come risultato "false"

#creazione di una funzione più velocemnte tramite lambda

funzione_Somma= lambda x,y:x+y

ris=funzione_Somma(2,3)

print(ris)

i numeri della list comorendion [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 2, 4, 6, 8, 10]
5


esempio con list comprention


In [4]:
lista= [1000,2000]

def calcola(salariobase, bonus=.1):
    return salariobase* (1+bonus)

salario= [calcola(salario) for salario in lista]

print(salario)

[1100.0, 2200.0]


Stesso esempio con lambda

In [5]:
lista= [1000,2000]
funzione = [(lambda salariobase,bonus=.1: salariobase*(1+bonus))(salario) for salario in lista]



print(funzione)

[1100.0, 2200.0]


Modulo

per creare un file si fa:

In [6]:
%%writefile modulo.py
# per modificarlo devo fare %%writefile -a modulo.py
def somma(x,y):
    return x+y

Overwriting modulo.py


Per usare il mio modulo

In [7]:
import modulo

modulo.somma(1,2)

3

NumPy

In [8]:
#installazione 

%conda install numpy

#importazione


import numpy as np





Retrieving notices: done
Channels:
 - defaults
Platform: osx-arm64
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [9]:
#uso su array

a=np.array([1,2,3,4,5])

print(a)

#per capire il tipo di dato

a.dtype

#posso dire io che tipo di dato voglio

afloat=np.array([1,2],dtype="float")

afloat



[1 2 3 4 5]


array([1., 2.])

Indicizzazione booleana: estrarre elementi che soddisfano un certa condizione oppure per modificare gli elementi che hanno una certa condizione

In [15]:
a=np.array([1,2,3,4,5])

b=a[a<3]

print(b)

print(np.any(a>5))
print(np.all(a<6))

#array 1d dove i valori i dati sulle vendite e devo trovare i valori che sono maggiori di 30000

vendite = np.array([34_000,45_000,2])
print("array iniziale",vendite)

array_vero_falso=vendite>30000
print(array_vero_falso)

print("prova",np.where(vendite>30000))

salary_array=np.where(vendite<30000,4,vendite)
print(salary_array)

#random
import random
salary = [random.randint(100000,150000) for num in range(10)]
print(salary)

#sommacululativa

cumulativa=np.cumsum(vendite)

print(cumulativa)

#prodotto scalare e vettoriale

#operazioni statistiche: media,mediana ecc

media=np.mean(vendite)
media

#indice del valore massimo o minimo

print(np.argmax(vendite))#ritorna l'indice
print(np.argmin(vendite))

#campionemento causale

print(np.random.normal(loc=0.0,scale=1.0,size=None)) #vanno dai valori da -1 a 2 loc=valore medio, scale=varianza(quanto cambia dal mio valore media)

print(np.random.randint(0,10,3)) #valore minimo, valore massimo, grandezza array

#ATTENZIONE !!
a=np.array([0.1+0.2,2.0])
b=np.array([0.3,2.0])

print(a==b)
print(np.isclose(a,b))

#caricare e salvare file numpy

#caricare dati

passeggeri=np.loadtxt('ciao.csv',delimiter=",",dtype=str)
print(passeggeri)

#salvare

array_random=(np.random.randint(0,10,3))
np.savetxt('ciao.csv',array_random)


[1 2]
False
True
array iniziale [34000 45000     2]
[ True  True False]
prova (array([0, 1]),)
[34000 45000     4]
[140768, 102031, 132154, 125383, 100999, 128177, 130323, 140961, 123610, 109971]
[34000 79000 79002]
1
2
-0.9965822620202727
[6 8 6]
[False  True]
[ True  True]
['2.000000000000000000e+00' '7.000000000000000000e+00'
 '2.000000000000000000e+00']


MATRICI

In [11]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

b=np.zeros((3,2))#matrici che hano tutti valore 0 con 3 righe e 2 colonnne
print(b)

#creare una matrice con arrange e shape

c=np.arange(20).reshape((4,5)) #vlaori che vanno da 0 a 30 e la forma è di 4 righe e 5 colonne
print(c)
#se voglio seleizonare il numero 3 da a come devo fare?

a[0][-1]

#se lo devo fare in una matrice, se voglio trovare l'elemento con riga di indice 1 e colonna con indice 2

c[1,2]

#FANDCY INDEXING: selezionare più elementi

righe=np.array([0,2]) #riga o e riga 2
colonna=np.array([1,2]) #colonna 1 e colonna 2

print(c[righe,colonna])

#axis: operazioni su righe e colonne di una matrice

print(c.sum())#sommo tutta la matrice
print(c.sum(axis=0)) #rispetto alle colonne
print(c.sum(axis=1)) #rispetto alle righe

#operazioni tra matrici

f=np.array([[1,2],[2,3]])
g=np.array([[1,2],[2,3]])

print(f+g)

#array ndimensionali

array3d=np.array(([1,2],[2,3],[1,2],[2,3]))

print(array3d)

#vettorizzazione

c=[]

for i in range((len(f))):
    c.append(f[i]+g[i])
    
print(c)


[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 1 12]
190
[30 34 38 42 46]
[10 35 60 85]
[[2 4]
 [4 6]]
[[1 2]
 [2 3]
 [1 2]
 [2 3]]
[array([2, 4]), array([4, 6])]
